enum actionTypesNames {
  LOADING_SET = 'LOADING/SET',
  COLLAPSE_ERROR = 'ERROR/COLLAPSE',
  COLLAPSE_NOTIFICATION = 'NOTIFICATION/COLLAPSE',

  //APP_ERROR = 'APP/ERROR',
  CARDS_GET_REQUEST = 'CARDS/GET/REQUEST',
  CARDS_GET_SUCCESS = 'CARDS/GET/SUCCESS',
  CARDS_GET_ERROR = 'CARDS/GET/ERROR',

  CARD_ADD_REQUEST = 'CARD/ADD/REQUEST',
  CARD_ADD_SUCCESS = 'CARD/ADD/SUCCESS',
  CARD_ADD_ERROR = 'CARD/ADD/ERROR',

  CARD_DELETE_REQUEST = 'CARD/DELETE/REQUEST',
  CARD_DELETE_SUCCESS = 'CARD/DELETE/SUCCESS',
  CARD_DELETE_ERROR = 'CARD/DELETE/ERROR',

  WEATHER_GET_REQUEST = 'WEATHER/GET/REQUEST',
  WEATHER_GET_SUCCESS = 'WEATHER/GET/SUCCESS',
  WEATHER_GET_ERROR = 'WEATHER/GET/ERROR',
}

export default actionTypesNames;
